DROP TABLE IF EXISTS `balance_sheet_fill`;

CREATE TABLE `balance_sheet_fill`  (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `ts_code` VARCHAR(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT 'ts_code',
  `trade_date` DATE NOT NULL COMMENT 'trade date',
  `end_date` DATE NOT NULL COMMENT 'report period',
  `report_type` VARCHAR(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT 'report type',
  `comp_type` VARCHAR(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT 'company type',
  `end_type` VARCHAR(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT 'report period type',
  `total_share` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'total share',
  `cap_rese` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'capital reserve',
  `undistr_porfit` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'undistributed profit',
  `surplus_rese` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'surplus reserve',
  `special_rese` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'special reserve',
  `money_cap` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'monetary capital',
  `trad_asset` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'trading asset',
  `notes_receiv` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'notes receivable',
  `accounts_receiv` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'accounts receivable',
  `oth_receiv` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'other receivable',
  `prepayment` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'prepayment',
  `div_receiv` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'dividend receivable',
  `int_receiv` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'interest receivable',
  `inventories` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'inventories',
  `amor_exp` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'amortization expense',
  `nca_within_1y` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'non-current asset due within 1 year',
  `sett_rsrv` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'settlement reserve',
  `loanto_oth_bank_fi` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'loan to other bank financial institution',
  `premium_receiv` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'premium receivable',
  `reinsur_receiv` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'reinsurance receivable',
  `reinsur_res_receiv` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'reinsurance reserve receivable',
  `pur_resale_fa` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'purchase resale fa',
  `oth_cur_assets` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'other current assets',
  `total_cur_assets` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'total current assets',
  `fa_avail_for_sale` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'financial asset available for sale',
  `htm_invest` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'held-to-maturity investment',
  `lt_eqt_invest` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'long-term equity investment',
  `invest_real_estate` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'investment real estate',
  `time_deposits` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'time deposits',
  `oth_assets` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'other assets',
  `lt_rec` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'long-term receivable',
  `fix_assets` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'fixed assets',
  `cip` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'construction in progress',
  `const_materials` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'construction materials',
  `fixed_assets_disp` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'fixed assets disposal',
  `produc_bio_assets` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'productive biological assets',
  `oil_and_gas_assets` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'oil and gas assets',
  `intan_assets` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'intangible assets',
  `r_and_d` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'research and development',
  `goodwill` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'goodwill',
  `lt_amor_exp` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'long-term amortization expense',
  `defer_tax_assets` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'deferred tax assets',
  `decr_in_disbur` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'decrease in disbursed',
  `oth_nca` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'other non-current assets',
  `total_nca` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'total non-current assets',
  `cash_reser_cb` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'cash reserve with central bank',
  `depos_in_oth_bfi` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'deposit in other bank financial institution',
  `prec_metals` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'precious metals',
  `deriv_assets` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'derivative assets',
  `rr_reins_une_prem` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'reinsurance premium',
  `rr_reins_outstd_cla` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'reinsurance outstanding claim',
  `rr_reins_lins_liab` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'reinsurance liability',
  `rr_reins_lthins_liab` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'reinsurance long-term insurance liability',
  `refund_depos` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'refundable deposits',
  `ph_pledge_loans` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'pledge loans',
  `refund_cap_depos` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'refundable capital deposits',
  `indep_acct_assets` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'independent account assets',
  `client_depos` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'client deposits',
  `client_prov` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'client provision',
  `transac_seat_fee` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'transaction seat fee',
  `invest_as_receiv` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'investment as receivable',
  `total_assets` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'total assets',
  `lt_borr` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'long-term borrowings',
  `st_borr` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'short-term borrowings',
  `cb_borr` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'central bank borrowings',
  `depos_ib_deposits` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'deposits and borrowings from interbank',
  `loan_oth_bank` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'loan from other bank',
  `trading_fl` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'trading financial liabilities',
  `notes_payable` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'notes payable',
  `acct_payable` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'accounts payable',
  `adv_receipts` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'advance receipts',
  `sold_for_repur_fa` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'sold for repurchase financial assets',
  `comm_payable` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'commission payable',
  `payroll_payable` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'payroll payable',
  `taxes_payable` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'taxes payable',
  `int_payable` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'interest payable',
  `div_payable` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'dividend payable',
  `oth_payable` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'other payable',
  `acc_exp` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'accrued expense',
  `deferred_inc` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'deferred income',
  `st_bonds_payable` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'short-term bonds payable',
  `payable_to_reinsurer` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'payable to reinsurer',
  `rsrv_insur_cont` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'reserve for insurance contract',
  `acting_trading_sec` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'acting trading securities',
  `acting_uw_sec` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'acting underwriting securities',
  `non_cur_liab_due_1y` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'non-current liabilities due within 1 year',
  `oth_cur_liab` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'other current liabilities',
  `total_cur_liab` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'total current liabilities',
  `bond_payable` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'bond payable',
  `lt_payable` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'long-term payable',
  `specific_payables` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'specific payables',
  `estimated_liab` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'estimated liability',
  `defer_tax_liab` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'deferred tax liability',
  `defer_inc_non_cur_liab` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'deferred income non-current liability',
  `oth_ncl` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'other non-current liabilities',
  `total_ncl` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'total non-current liabilities',
  `depos_oth_bfi` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'deposits from other bank financial institution',
  `deriv_liab` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'derivative liability',
  `depos` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'deposits',
  `agency_bus_liab` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'agency business liabilities',
  `oth_liab` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'other liabilities',
  `prem_receiv_adva` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'premium received in advance',
  `depos_received` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'deposits received',
  `ph_invest` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'pledge of house',
  `reser_une_prem` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'reserve for unearned premium',
  `reser_outstd_claims` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'reserve for outstanding claims',
  `reser_lins_liab` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'reserve for life insurance liability',
  `reser_lthins_liab` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'reserve for long-term insurance liability',
  `indept_acc_liab` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'independent account liabilities',
  `pledge_borr` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'pledge borrowings',
  `indem_payable` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'indemnity payable',
  `policy_div_payable` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'policy dividend payable',
  `total_liab` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'total liabilities',
  `treasury_share` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'treasury share',
  `ordin_risk_reser` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'ordinary risk reserve',
  `forex_differ` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'foreign exchange difference',
  `invest_loss_unconf` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'investment loss unconfirmed',
  `minority_int` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'minority interest',
  `total_hldr_eqy_exc_min_int` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'total holder equity excluding minority interest',
  `total_hldr_eqy_inc_min_int` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'total holder equity including minority interest',
  `total_liab_hldr_eqy` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'total liabilities and holder equity',
  `lt_payroll_payable` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'long-term payroll payable',
  `oth_comp_income` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'other comprehensive income',
  `oth_eqt_tools` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'other equity tools',
  `oth_eqt_tools_p_shr` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'other equity tools per share',
  `lending_funds` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'lending funds',
  `acc_receivable` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'account receivable',
  `st_fin_payable` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'short-term financing payable',
  `payables` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'payables',
  `hfs_assets` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'held-for-sale assets',
  `hfs_sales` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'held-for-sale sales',
  `cost_fin_assets` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'cost of financial assets',
  `fair_value_fin_assets` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'fair value of financial assets',
  `contract_assets` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'contract assets',
  `contract_liab` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'contract liabilities',
  `accounts_receiv_bill` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'accounts receivable bill',
  `accounts_pay` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'accounts payable',
  `oth_rcv_total` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'other receivable total',
  `fix_assets_total` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'fixed assets total',
  `cip_total` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'construction in progress total',
  `oth_pay_total` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'other payables total',
  `long_pay_total` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'long-term payables total',
  `debt_invest` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'debt investment',
  `oth_debt_invest` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'other debt investment',
  `oth_eq_invest` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'other equity investment',
  `oth_illiq_fin_assets` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'other illiquid financial assets',
  `oth_eq_ppbond` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'other equity perpetual bond',
  `reciev_financing` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'receivable financing',
  `use_right_assets` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'use right assets',
  `lease_liab` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'lease liability',
  `receiv_financing` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'receivable financing',
  `update_flag` INT(1) NOT NULL COMMENT 'update flag',
  
  PRIMARY KEY (`id`)
  ) COMMENT = 'balance_sheet';


DROP TABLE IF EXISTS `balance_sheet`;

CREATE TABLE `balance_sheet`  (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `ts_code` VARCHAR(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT 'ts_code',
  `ann_date` DATE NOT NULL COMMENT 'announcement date',
  `f_ann_date` DATE NOT NULL COMMENT 'final announcement date',
  `end_date` DATE NOT NULL COMMENT 'report period',
  `report_type` VARCHAR(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT 'report type',
  `comp_type` VARCHAR(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT 'company type',
  `end_type` VARCHAR(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT 'report period type',
  `total_share` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'total share',
  `cap_rese` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'capital reserve',
  `undistr_porfit` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'undistributed profit',
  `surplus_rese` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'surplus reserve',
  `special_rese` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'special reserve',
  `money_cap` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'monetary capital',
  `trad_asset` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'trading asset',
  `notes_receiv` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'notes receivable',
  `accounts_receiv` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'accounts receivable',
  `oth_receiv` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'other receivable',
  `prepayment` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'prepayment',
  `div_receiv` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'dividend receivable',
  `int_receiv` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'interest receivable',
  `inventories` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'inventories',
  `amor_exp` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'amortization expense',
  `nca_within_1y` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'non-current asset due within 1 year',
  `sett_rsrv` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'settlement reserve',
  `loanto_oth_bank_fi` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'loan to other bank financial institution',
  `premium_receiv` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'premium receivable',
  `reinsur_receiv` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'reinsurance receivable',
  `reinsur_res_receiv` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'reinsurance reserve receivable',
  `pur_resale_fa` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'purchase resale fa',
  `oth_cur_assets` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'other current assets',
  `total_cur_assets` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'total current assets',
  `fa_avail_for_sale` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'financial asset available for sale',
  `htm_invest` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'held-to-maturity investment',
  `lt_eqt_invest` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'long-term equity investment',
  `invest_real_estate` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'investment real estate',
  `time_deposits` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'time deposits',
  `oth_assets` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'other assets',
  `lt_rec` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'long-term receivable',
  `fix_assets` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'fixed assets',
  `cip` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'construction in progress',
  `const_materials` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'construction materials',
  `fixed_assets_disp` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'fixed assets disposal',
  `produc_bio_assets` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'productive biological assets',
  `oil_and_gas_assets` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'oil and gas assets',
  `intan_assets` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'intangible assets',
  `r_and_d` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'research and development',
  `goodwill` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'goodwill',
  `lt_amor_exp` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'long-term amortization expense',
  `defer_tax_assets` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'deferred tax assets',
  `decr_in_disbur` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'decrease in disbursed',
  `oth_nca` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'other non-current assets',
  `total_nca` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'total non-current assets',
  `cash_reser_cb` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'cash reserve with central bank',
  `depos_in_oth_bfi` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'deposit in other bank financial institution',
  `prec_metals` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'precious metals',
  `deriv_assets` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'derivative assets',
  `rr_reins_une_prem` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'reinsurance premium',
  `rr_reins_outstd_cla` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'reinsurance outstanding claim',
  `rr_reins_lins_liab` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'reinsurance liability',
  `rr_reins_lthins_liab` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'reinsurance long-term insurance liability',
  `refund_depos` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'refundable deposits',
  `ph_pledge_loans` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'pledge loans',
  `refund_cap_depos` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'refundable capital deposits',
  `indep_acct_assets` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'independent account assets',
  `client_depos` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'client deposits',
  `client_prov` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'client provision',
  `transac_seat_fee` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'transaction seat fee',
  `invest_as_receiv` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'investment as receivable',
  `total_assets` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'total assets',
  `lt_borr` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'long-term borrowings',
  `st_borr` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'short-term borrowings',
  `cb_borr` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'central bank borrowings',
  `depos_ib_deposits` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'deposits and borrowings from interbank',
  `loan_oth_bank` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'loan from other bank',
  `trading_fl` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'trading financial liabilities',
  `notes_payable` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'notes payable',
  `acct_payable` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'accounts payable',
  `adv_receipts` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'advance receipts',
  `sold_for_repur_fa` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'sold for repurchase financial assets',
  `comm_payable` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'commission payable',
  `payroll_payable` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'payroll payable',
  `taxes_payable` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'taxes payable',
  `int_payable` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'interest payable',
  `div_payable` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'dividend payable',
  `oth_payable` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'other payable',
  `acc_exp` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'accrued expense',
  `deferred_inc` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'deferred income',
  `st_bonds_payable` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'short-term bonds payable',
  `payable_to_reinsurer` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'payable to reinsurer',
  `rsrv_insur_cont` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'reserve for insurance contract',
  `acting_trading_sec` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'acting trading securities',
  `acting_uw_sec` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'acting underwriting securities',
  `non_cur_liab_due_1y` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'non-current liabilities due within 1 year',
  `oth_cur_liab` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'other current liabilities',
  `total_cur_liab` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'total current liabilities',
  `bond_payable` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'bond payable',
  `lt_payable` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'long-term payable',
  `specific_payables` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'specific payables',
  `estimated_liab` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'estimated liability',
  `defer_tax_liab` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'deferred tax liability',
  `defer_inc_non_cur_liab` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'deferred income non-current liability',
  `oth_ncl` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'other non-current liabilities',
  `total_ncl` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'total non-current liabilities',
  `depos_oth_bfi` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'deposits from other bank financial institution',
  `deriv_liab` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'derivative liability',
  `depos` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'deposits',
  `agency_bus_liab` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'agency business liabilities',
  `oth_liab` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'other liabilities',
  `prem_receiv_adva` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'premium received in advance',
  `depos_received` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'deposits received',
  `ph_invest` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'pledge of house',
  `reser_une_prem` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'reserve for unearned premium',
  `reser_outstd_claims` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'reserve for outstanding claims',
  `reser_lins_liab` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'reserve for life insurance liability',
  `reser_lthins_liab` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'reserve for long-term insurance liability',
  `indept_acc_liab` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'independent account liabilities',
  `pledge_borr` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'pledge borrowings',
  `indem_payable` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'indemnity payable',
  `policy_div_payable` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'policy dividend payable',
  `total_liab` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'total liabilities',
  `treasury_share` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'treasury share',
  `ordin_risk_reser` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'ordinary risk reserve',
  `forex_differ` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'foreign exchange difference',
  `invest_loss_unconf` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'investment loss unconfirmed',
  `minority_int` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'minority interest',
  `total_hldr_eqy_exc_min_int` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'total holder equity excluding minority interest',
  `total_hldr_eqy_inc_min_int` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'total holder equity including minority interest',
  `total_liab_hldr_eqy` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'total liabilities and holder equity',
  `lt_payroll_payable` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'long-term payroll payable',
  `oth_comp_income` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'other comprehensive income',
  `oth_eqt_tools` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'other equity tools',
  `oth_eqt_tools_p_shr` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'other equity tools per share',
  `lending_funds` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'lending funds',
  `acc_receivable` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'account receivable',
  `st_fin_payable` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'short-term financing payable',
  `payables` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'payables',
  `hfs_assets` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'held-for-sale assets',
  `hfs_sales` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'held-for-sale sales',
  `cost_fin_assets` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'cost of financial assets',
  `fair_value_fin_assets` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'fair value of financial assets',
  `contract_assets` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'contract assets',
  `contract_liab` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'contract liabilities',
  `accounts_receiv_bill` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'accounts receivable bill',
  `accounts_pay` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'accounts payable',
  `oth_rcv_total` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'other receivable total',
  `fix_assets_total` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'fixed assets total',
  `cip_total` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'construction in progress total',
  `oth_pay_total` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'other payables total',
  `long_pay_total` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'long-term payables total',
  `debt_invest` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'debt investment',
  `oth_debt_invest` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'other debt investment',
  `oth_eq_invest` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'other equity investment',
  `oth_illiq_fin_assets` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'other illiquid financial assets',
  `oth_eq_ppbond` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'other equity perpetual bond',
  `reciev_financing` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'receivable financing',
  `use_right_assets` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'use right assets',
  `lease_liab` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'lease liability',
  `receiv_financing` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'receivable financing',
  `update_flag` INT(1) NOT NULL COMMENT 'update flag',
  
  PRIMARY KEY (`id`)
  ) COMMENT = 'balance_sheet_fill';