DROP TABLE IF EXISTS `cash_flow`;

CREATE TABLE `cash_flow`  (
    `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
    `ts_code` VARCHAR(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'ts_code',
    `trade_date` DATE NOT NULL COMMENT 'trade date',
    `end_date` DATE NOT NULL COMMENT 'report period',
    `report_type` VARCHAR(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT 'report type',
    `comp_type` VARCHAR(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT 'company type',
    `end_type` VARCHAR(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT 'report period type',
    `net_profit` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'net profit',
    `finan_exp` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'financial expense',
    `c_fr_sale_sg` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'cash flow from sale of goods',
    `recp_tax_rends` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'cash flow from tax refunds',
    `n_depos_incr_fi` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'net increase in deposits from financial institutions',
    `n_incr_loans_cb` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'net increase in loans from central bank',
    `n_inc_borr_oth_fi` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'net increase in borrowings from other financial institutions',
    `prem_fr_orig_contr` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'premiums received for original contracts',
    `n_incr_insured_dep` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'net increase in insured deposits',
    `n_reinsur_prem` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'net increase in reinsurance premiums',
    `n_incr_disp_tfa` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'net increase in disposal of trading financial assets',
    `ifc_cash_incr` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'net increase in income from current operations',
    `n_incr_disp_faas` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'net increase in disposal of financial assets available for sale',
    `n_incr_loans_oth_bank` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'net increase in loans and advances to other banks',
    `n_cap_incr_repur` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'net increase in capital repurchase',
    `c_fr_oth_operate_a` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'cash flow from other operating activities',
    `c_inf_fr_operate_a` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'cash inflow from operating activities',
    `c_paid_goods_s` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'cash paid for goods and services',
    `c_paid_to_for_empl` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'cash paid to and for employees',
    `c_paid_for_taxes` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'cash paid for taxes',
    `n_incr_clt_loan_adv` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'net increase in client loans and advances',
    `n_incr_dep_cbob` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'net increase in deposits and placements from banks and other financial institutions',
    `c_pay_claims_orig_inco` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'cash paid for original insurance contract claims',
    `pay_handling_chrg` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'cash paid for handling charges and commission',
    `pay_comm_insur_plcy` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'cash paid for commission of original insurance contracts',
    `oth_cash_pay_oper_act` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'other cash paid for operating activities',
    `st_cash_out_act` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'subtotal of cash outflow from operating activities',
    `n_cashflow_act` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'net cash flows from operating activities',
    `oth_recp_ral_inv_act` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'other cash received related to investing activities',
    `c_disp_withdrwl_invest` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'cash received from disposal of investments',
    `c_recp_return_invest` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'cash received from returns on investments',
    `n_recp_disp_fiolta` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'net cash received from disposal of fixed, intangible and other long-term assets',
    `n_recp_disp_sobu` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'net cash received from disposal of subsidiaries, other operating units and other business units',
    `stot_inflows_inv_act` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'subtotal of cash inflow related to investing activities',
    `c_pay_acq_const_fiolta` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'cash paid to acquire fixed, intangible and other long-term assets',
    `c_paid_invest` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'cash paid to acquire investments',
    `n_disp_subs_oth_biz` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'net cash received from disposal of subsidiaries, other operating units and other business units',
    `oth_pay_ral_inv_act` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'other cash paid related to investing activities',
    `n_incr_pledge_loan` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'net increase in pledged loans',
    `stot_out_inv_act` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'subtotal of cash outflow related to investing activities',
    `n_cashflow_inv_act` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'net cash flows from investing activities',
    `c_recp_borrow` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'cash received from borrowings',
    `proc_issue_bonds` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'proceeds from issuance of bonds',
    `oth_cash_recp_ral_fnc_act` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'other cash received related to financing activities',
    `stot_cash_in_fnc_act` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'subtotal of cash inflow related to financing activities',
    `free_cashflow` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'free cash flow',
    `c_prepay_amt_borr` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'cash received from prepayments',
    `c_pay_dist_dpcp_int_exp` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'cash paid for interest expenses, distribution expenses and commission paid',
    `incl_dvd_profit_paid_sc_ms` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'including: dividends paid, profit distribution paid to minority shareholders',
    `oth_cashpay_ral_fnc_act` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'other cash paid related to financing activities',
    `stot_cashout_fnc_act` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'subtotal of cash outflow related to financing activities',
    `n_cash_flows_fnc_act` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'net cash flows from financing activities',
    `eff_fx_flu_cash` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'effect of foreign exchange changes on cash',
    `n_incr_cash_cash_equ` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'net increase in cash and cash equivalents',
    `c_cash_equ_beg_period` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'cash and cash equivalents at beginning of period',
    `c_cash_equ_end_period` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'cash and cash equivalents at end of period',
    `c_recp_cap_contrib` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'cash received from capital contributions',
    `incl_cash_rec_saims` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'including: cash received from sales of investment-related assets',
    `uncon_invest_loss` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'unrecognized investment loss provisions',
    `prov_depr_assets` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'provision of assets depreciation',
    `depr_fa_coga_dpba` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'depreciation of fixed assets, cost of goods sold, depreciation of production biological assets',
    `amort_intang_assets` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'amortization of intangible assets',
    `lt_amort_deferred_exp` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'long-term amortization expenses',
    `decr_deferred_exp` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'decrease in deferred expenses',
    `incr_acc_exp` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'increase in accrued expenses',
    `loss_disp_fiolta` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'loss on disposal of fixed, intangible and other long-term assets',
    `loss_scr_fa` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'loss on fixed asset retirement',
    `loss_fv_chg` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'loss on fair value change',
    `invest_loss` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'investment loss',
    `decr_def_inc_tax_assets` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'decrease in deferred income tax assets',
    `incr_def_inc_tax_liab` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'increase in deferred income tax liabilities',
    `decr_inventories` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'decrease in inventories',
    `decr_oper_payable` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'decrease in operating payables',
    `incr_oper_payable` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'increase in operating payables',
    `others` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'others',
    `im_net_cashflow_oper_act` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'minority shareholders effect on cash',
    `conv_debt_into_cap` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'debt to equity swap',
    `conv_copbonds_due_within_1y` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'convertible bond that due within 1 year',
    `fa_fnc_leases` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'finance lease fixed assets',
    `im_n_incr_cash_equ` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'effect of exchange rate changes on cash and cash equivalents',
    `net_dism_capital_add` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'net disposal of capital assets',
    `net_cash_rece_sec` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'net increase in pledged loans',
    `credit_impa_loss` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'credit impairment loss',
    `use_right_asset_dep` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'use of rights and assets depreciation',
    `oth_loss_asset` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'other losses',
    `end_bal_cash` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'cash at the end of period',
    `beg_bal_cash` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'cash at the beginning of period',
    `end_bal_cash_equ` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'cash and cash equivalents at the end of period',
    `beg_bal_cash_equ` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'cash and cash equivalents at the beginning of period',
    `update_flag` VARCHAR(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'update flag',
    PRIMARY KEY (`id`) USING BTREE
    ) COMMENT = 'cash flow';

DROP TABLE IF EXISTS `cash_flow_fill`;

CREATE TABLE `cash_flow_fill`  (
    `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
    `ts_code` VARCHAR(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'ts_code',
    `ann_date` DATE NOT NULL COMMENT 'announcement date',
    `f_ann_date` DATE NOT NULL COMMENT 'final announcement date',
    `end_date` DATE NOT NULL COMMENT 'report period',
    `report_type` VARCHAR(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT 'report type',
    `comp_type` VARCHAR(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT 'company type',
    `end_type` VARCHAR(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT 'report period type',
    `net_profit` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'net profit',
    `finan_exp` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'financial expense',
    `c_fr_sale_sg` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'cash flow from sale of goods',
    `recp_tax_rends` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'cash flow from tax refunds',
    `n_depos_incr_fi` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'net increase in deposits from financial institutions',
    `n_incr_loans_cb` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'net increase in loans from central bank',
    `n_inc_borr_oth_fi` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'net increase in borrowings from other financial institutions',
    `prem_fr_orig_contr` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'premiums received for original contracts',
    `n_incr_insured_dep` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'net increase in insured deposits',
    `n_reinsur_prem` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'net increase in reinsurance premiums',
    `n_incr_disp_tfa` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'net increase in disposal of trading financial assets',
    `ifc_cash_incr` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'net increase in income from current operations',
    `n_incr_disp_faas` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'net increase in disposal of financial assets available for sale',
    `n_incr_loans_oth_bank` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'net increase in loans and advances to other banks',
    `n_cap_incr_repur` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'net increase in capital repurchase',
    `c_fr_oth_operate_a` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'cash flow from other operating activities',
    `c_inf_fr_operate_a` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'cash inflow from operating activities',
    `c_paid_goods_s` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'cash paid for goods and services',
    `c_paid_to_for_empl` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'cash paid to and for employees',
    `c_paid_for_taxes` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'cash paid for taxes',
    `n_incr_clt_loan_adv` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'net increase in client loans and advances',
    `n_incr_dep_cbob` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'net increase in deposits and placements from banks and other financial institutions',
    `c_pay_claims_orig_inco` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'cash paid for original insurance contract claims',
    `pay_handling_chrg` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'cash paid for handling charges and commission',
    `pay_comm_insur_plcy` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'cash paid for commission of original insurance contracts',
    `oth_cash_pay_oper_act` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'other cash paid for operating activities',
    `st_cash_out_act` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'subtotal of cash outflow from operating activities',
    `n_cashflow_act` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'net cash flows from operating activities',
    `oth_recp_ral_inv_act` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'other cash received related to investing activities',
    `c_disp_withdrwl_invest` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'cash received from disposal of investments',
    `c_recp_return_invest` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'cash received from returns on investments',
    `n_recp_disp_fiolta` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'net cash received from disposal of fixed, intangible and other long-term assets',
    `n_recp_disp_sobu` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'net cash received from disposal of subsidiaries, other operating units and other business units',
    `stot_inflows_inv_act` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'subtotal of cash inflow related to investing activities',
    `c_pay_acq_const_fiolta` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'cash paid to acquire fixed, intangible and other long-term assets',
    `c_paid_invest` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'cash paid to acquire investments',
    `n_disp_subs_oth_biz` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'net cash received from disposal of subsidiaries, other operating units and other business units',
    `oth_pay_ral_inv_act` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'other cash paid related to investing activities',
    `n_incr_pledge_loan` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'net increase in pledged loans',
    `stot_out_inv_act` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'subtotal of cash outflow related to investing activities',
    `n_cashflow_inv_act` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'net cash flows from investing activities',
    `c_recp_borrow` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'cash received from borrowings',
    `proc_issue_bonds` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'proceeds from issuance of bonds',
    `oth_cash_recp_ral_fnc_act` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'other cash received related to financing activities',
    `stot_cash_in_fnc_act` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'subtotal of cash inflow related to financing activities',
    `free_cashflow` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'free cash flow',
    `c_prepay_amt_borr` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'cash received from prepayments',
    `c_pay_dist_dpcp_int_exp` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'cash paid for interest expenses, distribution expenses and commission paid',
    `incl_dvd_profit_paid_sc_ms` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'including: dividends paid, profit distribution paid to minority shareholders',
    `oth_cashpay_ral_fnc_act` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'other cash paid related to financing activities',
    `stot_cashout_fnc_act` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'subtotal of cash outflow related to financing activities',
    `n_cash_flows_fnc_act` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'net cash flows from financing activities',
    `eff_fx_flu_cash` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'effect of foreign exchange changes on cash',
    `n_incr_cash_cash_equ` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'net increase in cash and cash equivalents',
    `c_cash_equ_beg_period` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'cash and cash equivalents at beginning of period',
    `c_cash_equ_end_period` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'cash and cash equivalents at end of period',
    `c_recp_cap_contrib` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'cash received from capital contributions',
    `incl_cash_rec_saims` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'including: cash received from sales of investment-related assets',
    `uncon_invest_loss` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'unrecognized investment loss provisions',
    `prov_depr_assets` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'provision of assets depreciation',
    `depr_fa_coga_dpba` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'depreciation of fixed assets, cost of goods sold, depreciation of production biological assets',
    `amort_intang_assets` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'amortization of intangible assets',
    `lt_amort_deferred_exp` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'long-term amortization expenses',
    `decr_deferred_exp` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'decrease in deferred expenses',
    `incr_acc_exp` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'increase in accrued expenses',
    `loss_disp_fiolta` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'loss on disposal of fixed, intangible and other long-term assets',
    `loss_scr_fa` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'loss on fixed asset retirement',
    `loss_fv_chg` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'loss on fair value change',
    `invest_loss` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'investment loss',
    `decr_def_inc_tax_assets` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'decrease in deferred income tax assets',
    `incr_def_inc_tax_liab` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'increase in deferred income tax liabilities',
    `decr_inventories` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'decrease in inventories',
    `decr_oper_payable` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'decrease in operating payables',
    `incr_oper_payable` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'increase in operating payables',
    `others` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'others',
    `im_net_cashflow_oper_act` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'minority shareholders effect on cash',
    `conv_debt_into_cap` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'debt to equity swap',
    `conv_copbonds_due_within_1y` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'convertible bond that due within 1 year',
    `fa_fnc_leases` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'finance lease fixed assets',
    `im_n_incr_cash_equ` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'effect of exchange rate changes on cash and cash equivalents',
    `net_dism_capital_add` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'net disposal of capital assets',
    `net_cash_rece_sec` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'net increase in pledged loans',
    `credit_impa_loss` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'credit impairment loss',
    `use_right_asset_dep` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'use of rights and assets depreciation',
    `oth_loss_asset` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'other losses',
    `end_bal_cash` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'cash at the end of period',
    `beg_bal_cash` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'cash at the beginning of period',
    `end_bal_cash_equ` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'cash and cash equivalents at the end of period',
    `beg_bal_cash_equ` DECIMAL(20, 4) NULL DEFAULT NULL COMMENT 'cash and cash equivalents at the beginning of period',
    `update_flag` VARCHAR(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'update flag',
    PRIMARY KEY (`id`) USING BTREE
    ) COMMENT = 'cash flow fill';